updated to standard format

diff --git a/services/lambda/lambdaservice b/services/lambda/lambdaservice
--- a/services/lambda/lambdaservice
+++ b/services/lambda/lambdaservice
@@ -2,14 +2,35 @@
 
 # lambda service script
 
-# exec > >(tee -a /usr/local/osmosix/logs/service.log) 2>&1
+exec > >(tee -a /usr/local/osmosix/logs/service.log) 2>&1
 
 . /utils.sh
+
+
+# Print the env to the CCM UI for debugging. Remove this line for production.
+# Ues with:
+# sed -n '/718WPR53 ENV START/,/718WPR53 ENV END/p' /usr/local/cliqr/logs/gateway.log | \
+# head -n-1 | tail -n+2 | grep '=' | grep -v '\\n' > envfile
+#echo "${parentJobName} ENV START"
+#env
+#echo "${parentJobName} ENV END"
 
 cmd=$1
 SVCNAME="lambda1"
 export INSTALL_DIR="/usr/local/aws"
 
+if [ -n "${gitTag}" ]; then
+    tag="${gitTag}"
+else
+    tag="lambda"
+fi
+
+print_log "Tag/branch for code pull set to ${tag}"
+
+error () {
+    print_log "${1}"
+    exit 1
+}
 
 # the following should be parameters from the service
 
@@ -20,42 +41,37 @@ fi
 
 if [ -z "$lambdaRuntime" ];
 then
-	print_error "Runtime missing for Lambda function"
-	exit 119
+	error "Runtime missing for Lambda function"
 fi
 
 if [ -z "$lambdaHandler" ];
 then
-	print_error "Handler missing for Lambda function"
-	exit 118
+	error "Handler missing for Lambda function"
 fi
 
 if [ -z "$lambdaRole" ];
 then
-	print_error "Role missing for Lambda function"
-	exit 117
+	error "Role missing for Lambda function"
 fi
 
 if [ -z "$lambdaCodeS3Bucket" ];
 then
-	print_error "S3 Bucket containing function code missing"
-	exit 116
+	error "S3 Bucket containing function code missing"
 fi
 
 if [ -z "$lambdaCodeS3Key" ];
 then
-	print_error "S3 Key containing function code missing"
-	exit 115
+	error "S3 Key containing function code missing"
 fi
 
 if [ ! -z "$lambdaRegion" ];
 then
-	export region=$lambdaRegion;
+	region=$lambdaRegion;
 fi
 
 if [ ! -z "$region" ];
 then
-	export region="us-east-1";
+	region="us-east-1";
 fi
 
 
@@ -94,8 +110,7 @@ configureAWSCli(){
 
 	elif [ -z $CliqrCloudAccountPwd ] || [ -z $CliqrCloud_AccessSecretKey ];
 	then
-		print_error "Insufficient permissions to access the Cloud Account, contact your Admin for the Cloud Account Accessibility";
-		exit 127
+		error "Insufficient permissions to access the Cloud Account, contact your Admin for the Cloud Account Accessibility";
 	else
 		export AWS_ACCESS_KEY_ID="$CliqrCloudAccountPwd"
 		export AWS_SECRET_ACCESS_KEY="$CliqrCloud_AccessSecretKey"
@@ -103,18 +118,15 @@ configureAWSCli(){
 	fi
 
 	if [ -z $AWS_ACCESS_KEY_ID ];then
-			print_error "Cloud Account Access Key not found or couldn't generate with IAM role"
-			exit 127
+			error "Cloud Account Access Key not found or couldn't generate with IAM role"
 	fi
 
 	if [ -z $AWS_SECRET_ACCESS_KEY ];then
-			print_error "Cloud Account Secret Key not found or couldn't generate with IAM role"
-			exit 127
+			error "Cloud Account Secret Key not found or couldn't generate with IAM role"
 	fi
 
 	if [ -z $region ];then
-			print_error "Region Value is not set"
-			exit 127
+			error "Region Value is not set"
 	fi
 
 	export "AWS_DEFAULT_REGION"=$region
@@ -124,31 +136,27 @@ configureAWSCli(){
 
 createLambdaFunction(){
 
-	print_log "$(env)"
-	result=`which aws`
-	print_log "aws path is $result"
-	print_log "--no-verify-ssl lambda create-function --function-name $lambdaFunctionName --runtime $lambdaRuntime --handler $lambdaHandler --role $lambdaRole --code S3Bucket=$lambdaCodeS3Bucket,S3Key=$lambdaCodeS3Key"
+    command="aws --no-verify-ssl lambda create-function --function-name $lambdaFunctionName --runtime $lambdaRuntime --handler $lambdaHandler --role $lambdaRole --code S3Bucket=$lambdaCodeS3Bucket,S3Key=$lambdaCodeS3Key 2>&1"
 
-    result=`aws --no-verify-ssl lambda create-function --function-name $lambdaFunctionName --runtime $lambdaRuntime --handler $lambdaHandler --role $lambdaRole --code S3Bucket=$lambdaCodeS3Bucket,S3Key=$lambdaCodeS3Key 2>&1`
+    print_log $command
 
-    if [ $? -eq 0 ];
-    then
-        print_log "Successfully created the Lambda function $lambdaFunctionName"
-    else
-        print_error "Error in creating Lambda function $lambdaFunctionName"
-	print_error "result is $result"
-        exit 120
-    fi
+    msg=$(${command} 2>&1) || \
+        error "Failed to create Lambda function: ${msg}"
+
+    print_log "Successfully created the Lambda function $lambdaFunctionName"
 
 }
 
 deleteLambdaFunction(){
 
-    result=`aws lambda delete-function --function-name $lambdaFunctionName`
-    if [ $? -eq 0 ];
-    then
-        print_log "Lambda function $LambdaFunctionName deleted successfully"
-    fi
+    command="aws lambda delete-function --function-name $lambdaFunctionName"
+
+    print_log $command
+
+    msg=$(${command} 2>&1) || \
+        error "Failed to delete Lambda function: ${msg}"
+
+    print_log "Successfully deleted the Lambda function $lambdaFunctionName"
 
 }
 
@@ -164,9 +172,9 @@ case $cmd in
 		;;
 	stop)
 		echo "Service Action -  $cmd"
-        	echo "Installing AWS Cli Tools"
-        	installAWSCli
-        	configureAWSCli
+        echo "Installing AWS Cli Tools"
+        installAWSCli
+        configureAWSCli
 		deleteLambdaFunction
         	exit 0
 		;;
@@ -174,7 +182,7 @@ case $cmd in
 		echo "Service Action -  $cmd"
 		echo "Installing AWS Cli Tools"
 		installAWSCli
-        	configureAWSCli
+        configureAWSCli
 		deleteLambdaFunction
 		exit 0
 		;;
@@ -182,7 +190,7 @@ case $cmd in
 		echo "Service Action -  $cmd"
 		echo "Installing AWS Cli Tools"
 		installAWSCli
-        	configureAWSCli
+        configureAWSCli
 		createLambdaFunction
 		exit 0
 		;;
